# Generated by Django 5.1.2 on 2024-10-25 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_rename_address1_shippingaddress_sgipping_address2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='sgipping_address2',
            new_name='shipping_address2',
        ),
    ]
