# Generated by Django 5.1.2 on 2024-10-25 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_rename_sgipping_address2_shippingaddress_shipping_address2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shopping_full_name',
            new_name='shipping_full_name',
        ),
    ]
